version: '3'

volumes:
  local_postgres_data: {}
  local_postgres_data_backups: {}

services:
  django: &django
    build:
      context: .
      dockerfile: compose/local/django/Dockerfile
    image: urevent_local_django
    depends_on:
      - postgres
    volumes:
      - .:/app
    env_file:
      -  ../.envs/.local/.django
      - ../.envs/.local/.postgres
    ports:
      - "8000:8000"
    command: /start
