on:
  release:
    types: [created]

name: Deploy to Amazon ECS

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Create File
      run:  dummy.pem << ${{ secrets.AWS_SUPER_KEY }}
    - name: Add Permissions
      run:  chmod 400 dummy.pem
    - name: Call File
      run:  ssh -i dummy.pem ${{ secrets.AWS_USER }}@${{ secrets.AWS_HOST }} /home/${{ secrets.AWS_PATH }}
