name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - run: ls /
    - run: ls $HOME
    - name: Set environment variables
      run: |
        echo ::set-env name=COMPOSE_FILE::actions.yml
    - name: Check Code
      run: docker-compose run --rm django flake8
    - name: Build with Docker
      run: docker-compose build
