name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: List
      run: echo ${{github}} && ls ${{github}} && ls && ls -al ${{github.HOME}}
    - name: Build with Docker
      run: docker-compose -f ${{github.HOME}}/actions.yml build
    - name: Check Code
      run: docker-compose run --rm django flake8
