name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - run: ls $HOME
    - run: ls $HOME/work/event_up-backend

    #- name: Set environment variables
    #  run: |
    #    echo ::set-env name=COMPOSE_FILE::./actions.yml
      # cp local.yml docker-compose.yml
    - name: Build with Docker
      run: docker-compose build
    - name: Check Code
      run: docker-compose run --rm django flake8
