name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: List
      run: ls -al ./ && ls ls -al ../../../
    - name: Check Code
      run: docker-compose run --rm django flake8
    - name: Build with Docker
      run: docker-compose -f actions.yml build
