name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master, develop]
    
jobs:
  clean:
    runs-on: ubuntu-latest
    steps:
      - name: clean code
        run: docker-compose run --rm django flake8

      - name: Build the Docker image
        run: docker-compose -f ./actions.yml build

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Build and push Docker images
      uses: docker/build-push-action@v1.1.0
      with:
        path: ./actions.yml
        cache_froms: eventup_local_django, eventup_production_postgres, eventup_local_celeryworker, eventup_local_celerybeat, eventup_local_flower
