name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master, develop]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      
      # Build
      - name: Build docker images using cache
        uses: whoan/docker-build-with-cache-action@v5
        with:
          image_name: 'Build-Docker-Image'
          dockerfile: actions.yml
          # build_extra_args: # optional
            
      # ADD Codecov
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
      
      # Save 
      - name: Docker Lint
        uses: luke142367/Docker-Lint-Action@v1.1.1
        with:
          target: build-docker
          run: docker-compose run --rm django flake8
  
