name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master, develop]
    
jobs:
  :
     
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Build and push Docker images
      # You may pin to the exact commit or the version.
      # uses: docker/build-push-action@92e71463491f2d026a477188b8ad3a0fdd9d672c
      uses: docker/build-push-action@v1.1.0
      with:
        # Path to the build context
        path: /home/runner/work/event_up-backend/actions.yml
        # Sets the target stage to build
        #target: # optional
        # Always attempt to pull a newer version of the image
        #always_pull: # optional
        # Comma-delimited list of build-time variables
        #build_args: # optional
        # Comma-delimited list of images to consider as cache sources
        cache_froms: eventup_local_django, eventup_production_postgres, eventup_local_celeryworker, eventup_local_celerybeat, eventup_local_flower
