name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: docker build
        uses: actions/docker/cli@master
        with:
          args: build -t Z-Devs-platzi/event_up-backend .
